langauge: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
  chrome: stable
dist: trusty
script:
- yarn
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
- gem install bundler:2.1.4
deploy:
  provider: heroku
  api_key:
    secure: 040Y6pUFPaJxBphExlW51FOUryRvErchn2/gEjkXT9vv3zKF0q7gKT+QiLjmKWYex2WPOsleoRNp7GtzrdvKFHFYhTZ0NCXQ0/KW7Zn5sL+2hIeNJisvfdC74oD0hJfOgUkzljK6hnqOEOwO7AfRcWvB89zkCNfraAnIdAIhtfhMILmFTnTnh1JBwxCrGhxF8E+SSr5sZ6AnrFZgfPRMgrvV/F7aq1NOaWxcF5PrL0X1eYq811jeBN8FplBLFQM4lXPWaCzK5uLHI2dOrlwIuUxfzQLYXPmjDg+C2JETzdfoYlWGEObCW2iGTQDERuL7GDvKPBp9JUtFfzNP2KgOApdpMV/GH4vX77o8bHkMNWgRUmaruT32jNNye5KtbTK8ZSDbrDIsuzpJJBqKB4hxzWVAzX9Zfe+9d3thNOlnPFNUMh/x0ockLLewjUc7rXvXjARBzYUZC7nnNopQoYqKpEhvVQv084uyqri4jqWb4qjFeU4fjsvwxoN6zcBqo22ucdpNyvKx2oehhKN67rRgYp+i9bX/BW5bma2mcU0d2RSO2IICDaL57HrrxQK38MKtbFAiPHoqf2I2A+CPyIUgLW96f0J5q58c6/CTCBfNqWKF+gGeqoaDN/h6gQL4bVFsfc8kyi5gGYkZsZ7AzhlhiwCXdJHD4+yzCbtbKMxNV+E=
  app: pacific-sierra-45332
  run: rails db:migrate
