langauge: ruby
sudo: false
cache:
  bundler: true
  directories:
  - node_modules
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
  chrome: stable
dist: xenial
before_install:
- yes | gem update --system --force
- gem install bundler
script:
- yarn
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: 5YRAA9AjJZdmkQBmxdQEAR4Jg3gQ7AVhd0oZdywYMrX6lx7sOMLB3pH6+5FIEfUXoDeAtb7tZnRHp886O0/c60X+1o0+Ztj/8ct5ls0kHXdGa8eZU3xjHqkbeD9DgIsf2mPS0w7kmXdc/kKyAe4aj8yepXDt4AsoBif3oHA2+O0X8MoQ6KYArJ/VHOSsekzOkp1lYq6iO2/TLzGCcyFd1P2a+R+bk4gHYUkOsmE0x1qmt3JIkUKmxX+aTB2L+3M6ASLtKLLm/DoGAZbcnRE8q/EamhAGaP4yHQrVbvvaTNj2/FnkjUDAVNG9vDmEyIsaCsxWc4AGXqZMJxBs2lZJsT7DEGb7SdkNkC4VJFu8unP8+P8MtTMQLm6OOtgOKbd/kHK4U+kD/B73pWsPpJjhZl44oE+x5oZHQ1kApGNi2EsM8gtsJfnt7/IjbWI/e/jqhT452lDRtw++JKhJlRwv594GdI+cE0vxDFy1tJPc3NlcvLkfvYtYRSDpLUFrX33djdCVVoIU44m6BqOBfQQx33yxCElvgZ98ipiFX7w4gxTTAfmdJtKCsGvhnRVDbWwRSxRavH2Q/BmGHHgpvMduI0a7yecjrVWHTMfC894mXJERaAdETKlcypH+yS+sJmVxyJUW/l5YTexBtppz/LNh66OuAnCNpDy8un2e8UqY+WQ=
  app: pacific-sierra-45332
  on:
    repo: dborski/brownfield-of-dreams
  skip_cleanup: 'true'
